### PR TITLE
Request feedback and permission to merge and permission to merge Japanese Food into Main.

### PR DESCRIPTION
**Pull request by Kongkawee**
Added 5 Japanese menu.
- Added description and pictures.
- Create hyperlink.

### CODE REVIEW

**Comment by Pichayanon** [comment]
In part of picture in menu.md, you forget to set size of your picture.

**Comment by Kongkawee** [comment]
I fixed the picture size.

**Comment by Nuafah** [comment]
looks great ready to be merge.

**Comment by J-Jullaphong** [comment]
Looks good to me too.

**Pull request merged**
